### ISSUE TITLE
Métodos não funcionam

### ISSUE THREAD

**Issue by eversonaguiar** [pandavideo/examples#1]
Olá, 

Dentro da aplicação que estou trabalhando, faço o carregamento do vídeo via javascript e preciso fazer com que ao carregar um vídeo, ele comece executar automaticamente. Nenhum dos métodos que utilizei foi possível executar tal ação. Também não consegui utilizar o método destroy();

Consegui carregar o vídeo, fazer as personalizações visuais, mas, os demais métodos não funcionaram. 

Teria um exemplo prático com o autoplay, funcionando com áudio, autofullscreen e também com a aplicação do método destroy()? 

Obs.: api.v2.js 

Obrigado!

**Comment by cabraljv** [comment]
Olá, o autoplay com áudio é bloqueado pelo próprio browser caso o usuário não tenha interagido com a página (se for o seu caso).

Sobre o destroy, poderia compartilhar o snippet de código de como está utilizando a api e o método?

**Comment by eversonaguiar** [comment]
O js está assim:

     

            $.getScript('https://player.pandavideo.com.br/api.v2.js', function () {
                window.pandascripttag = window.pandascripttag || [];
                window.pandascripttag.push(function () {
                    const player = new PandaPlayer('panda-player', {
                        video_id: video_id,
                        library_id: library_id,
                        defaultStyle: true,
                        playerConfigs: {
                            autoplay: true,
                            color: '10D199',
                            controls: "play-large,play,progress,current-time,volume,captions,settings,pip,fullscreen",
                            preload: false,
                            saveProgress: true,
                            mutedIndicatorIcon: false,
                            alternativeProgress: false,
                            startTime: ''
                        },
                        onReady: () => {
                            document.getElementById('j_videoClose').onclick = function () {
                                player.destroy();
                            };
                        }
                    });
                });
            });




o retorno está:
![image](https://user-images.githubusercontent.com/31116350/216137625-e1704f09-dd94-45cd-a667-691a32213d08.png)


Nesse caso, o cliente quer que seja carregado via modal bootstrap, mas tentei também em um arquivo separado e o destroy também não funcionou.

**Comment by cabraljv** [comment]
Fixed

**Comment by lafraia** [comment]
Olá @eversonaguiar poderia fazer uns testes e nos avisar se deu tudo certo?

Qualquer coisa, o @cabraljv pode responder com dúvidas da implementação que pode aparecer.

Fico no aguardo do seu feedback.
